spring.application.name=demo

# PostgreSQL connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=newpassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========== L.iquibase Configuration ==========
# ???????? Liquibase
spring.liquibase.enabled=true

# ???? ? ???????? changelog ?????
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# ????????? ?????????????? ???????? ?????? Hibernate (?????? Liquibase ????????? ??????)
spring.jpa.hibernate.ddl-auto=none

# (???????????) ????? ??, ???? ??????????? ?? public
# spring.liquibase.default-schema=public

# (???????????) ??????? ??? ???????? ??????? ????????
# spring.liquibase.database-change-log-table=databasechangelog
# spring.liquibase.database-change-log-lock-table=databasechangeloglock